workflows:
  android-workflow:
    name: Android Workflow
    scripts:
      - name: Generate Gradle Wrapper
        script: |
          cd android
          # یہ کمانڈ وہ تمام فائلیں خود بنا دے گی جو غائب ہیں
          gradle wrapper --gradle-version 7.5
      - name: Build APK
        script: |
          flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      
