workflows:
  android-workflow:
    name: My Player Build
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Set up Gradle Wrapper
        script: | 
          cd android
          flutter symbol-upload android
      - name: Build APK
        script: | 
          flutter pub get
          flutter build apk --release --no-tree-shake-icons
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      
